dataset:
  train_datasets:
    - name_or_path: rd211/Big-Math-RL-Verified-Filtered
      split: train
      ratio: 1.0
  max_train_examples: 8

train:
  number_of_problems_per_batch: 1
  num_samples_per_problem: 2
  per_device_train_batch_size: 2
  learning_rate: 5e-7
  beta: 0.001
  mu: 1
  epsilon: 0.2
  epochs: 1
  max_steps: 2
  batch_size_ref_model: 1
  save_policy_to_disk_every_n: 1

teacher_model:
  model_name_or_path: Qwen/Qwen2.5-7B-Instruct
  attn_implementation: flash_attention_2
  vllm:
    temperature: 1.0
    max_length: 4096
    max_num_seqs: 64
    gpu_memory_utilization: 0.30
    number_of_gpus_per_instance: 4
    max_number_of_instances: 1
    load_and_unload: true
    use_v0: true
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 4096
    max_num_seqs: 64
    gpu_memory_utilization: 0.30
    number_of_gpus_per_instance: 4
    max_number_of_instances: 1
    use_v0: false
    load_and_unload: true

judge_model:
  model_name_or_path: Qwen/Qwen2.5-14B-Instruct-AWQ
  vllm:
    temperature: 0.6
    max_length: 4096
    max_num_seqs: 64
    gpu_memory_utilization: 0.30
    number_of_gpus_per_instance: 4
    max_number_of_instances: 1
    load_and_unload: false
    use_v0: false

reward_model:
  model_name_or_path: Answer

huggingface:
  name: <huggingface_name>
  push_to_hub: false

logging:
  wandb: true
  wandb_project: train-rl
  wandb_run_name: Qwen2.5-7B-Instruct-AWS-DryRun
  run_group: aws-dryrun
  wandb_tags: ["7b", "aws", "dryrun"]
  save_dir: checkpoints/7b-aws-dryrun
  save_steps: 1

generation:
  extra_penalty_for_rejected_judges: 1.0
  ignore_rejected_judge: false
  use_experimental_shared_memory: false
  max_turns: 4
  max_tokens_in_conversation: 4096
  max_tokens_per_turn: 256
  max_tokens_per_student_attempt: 512
  max_tokens_per_judge_attempt: 512
  number_student_attempts: 2
  number_judge_attempts: 1

